version: "3.9"

volumes:
  pg_project:

services:
  pg_db:
    image: 'postgres:latest'
    restart: always
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - pg_project:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432